"""initial schema

Revision ID: 3d2fa06e2726
Revises: 
Create Date: 2026-08-18 21:30:14.793238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgcrypto provides gen_random_uuid(), used as the server_default for every
    # table's UUID primary key so rows inserted outside the ORM still get valid ids.
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'OPERATIONS_ADMIN', 'SUPPORT_ADMIN', 'COMPLIANCE_ADMIN', name='admin_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('opportunities',
    sa.Column('kind', sa.Enum('FINANCING', 'INSURANCE', name='opportunity_kind_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimated_premium', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.Enum('WALLET', 'BANK', 'PAYMENT', 'BUSINESS', 'CASH', name='provider_category_enum'), nullable=False),
    sa.Column('availability', sa.Enum('DEMO', 'PARTNER', 'COMING_SOON', 'AVAILABLE', name='provider_availability_enum'), server_default='DEMO', nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('health_status', sa.Enum('HEALTHY', 'WARNING', 'SANDBOX', 'DOWN', name='provider_health_status_enum'), nullable=True),
    sa.Column('uptime', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_code'), 'providers', ['code'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'SUSPENDED', name='user_status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=100), nullable=True),
    sa.Column('financial_goal', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admin_refresh_tokens',
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['admin_refresh_tokens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_refresh_tokens_token_hash'), 'admin_refresh_tokens', ['token_hash'], unique=True)
    op.create_table('audit_logs',
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('ADMIN_LOGIN', 'OVERVIEW_VIEWED', 'USER_VIEWED', 'BUSINESS_VIEWED', 'TRANSACTION_VIEWED', 'PROVIDER_VIEWED', 'CONNECTION_VIEWED', 'CONSENT_VIEWED', 'RISK_VIEWED', 'AUDIT_LOG_VIEWED', 'SUPPORT_TICKET_VIEWED', name='audit_action_enum'), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('activity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='business_activity_enum'), server_default='MEDIUM', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'SUSPENDED', name='business_status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_passports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('income_consistency', sa.Integer(), nullable=False),
    sa.Column('savings_behavior', sa.Integer(), nullable=False),
    sa.Column('payment_activity', sa.String(length=20), nullable=False),
    sa.Column('repayment_behavior', sa.Integer(), nullable=False),
    sa.Column('financial_record_completeness', sa.Integer(), nullable=False),
    sa.Column('business_activity_duration', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('savings_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', name='savings_goal_status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_members',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'STAFF', 'VIEWER', name='business_member_role_enum'), server_default='OWNER', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'user_id', name='uq_business_member')
    )
    op.create_table('consents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'PENDING', 'REVOKED', 'EXPIRED', name='consent_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passport_shares',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('passport_id', sa.UUID(), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passport_id'], ['financial_passports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('DEMO', 'LIVE', name='connection_mode_enum'), server_default='DEMO', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONNECTED', 'SYNCING', 'ERROR', 'REVOKED', name='connection_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_alerts',
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='risk_level_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', name='risk_status_enum'), server_default='OPEN', nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'NORMAL', 'LOW', name='support_priority_enum'), server_default='NORMAL', nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'RESOLVED', name='support_status_enum'), server_default='OPEN', nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='transaction_type_enum'), nullable=False),
    sa.Column('source', sa.Enum('PROVIDER_API', 'BANK_FEED', 'MANUAL', 'QR', name='transaction_source_enum'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='NPR', nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'PENDING', 'FAILED', 'FLAGGED', name='transaction_status_enum'), server_default='COMPLETED', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['provider_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_external_reference'), 'transactions', ['external_reference'], unique=False)
    op.create_check_constraint('ck_transactions_amount_positive', 'transactions', 'amount > 0')
    op.create_check_constraint('ck_savings_goals_target_positive', 'savings_goals', 'target_amount > 0')
    # ### end Alembic commands ###

    # Admin list-read convenience view: joins business/provider/user display names
    # onto the canonical transaction row without denormalizing text columns onto
    # `transactions` itself. Read-only — admin routers select from it, they never
    # write through it.
    op.execute(
        """
        CREATE VIEW v_transactions_admin AS
        SELECT
            t.id,
            t.business_id,
            b.name AS business_name,
            b.owner_user_id AS user_id,
            u.name AS user_name,
            t.provider_id,
            p.name AS provider_name,
            p.code AS provider_code,
            t.type,
            t.source,
            t.category,
            t.amount,
            t.currency,
            t.status,
            t.description,
            t.external_reference,
            t.occurred_at,
            t.metadata,
            t.created_at,
            t.updated_at
        FROM transactions t
        JOIN businesses b ON b.id = t.business_id
        JOIN providers p ON p.id = t.provider_id
        JOIN users u ON u.id = b.owner_user_id
        """
    )


def downgrade() -> None:
    op.execute('DROP VIEW IF EXISTS v_transactions_admin')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_savings_goals_target_positive', 'savings_goals', type_='check')
    op.drop_constraint('ck_transactions_amount_positive', 'transactions', type_='check')
    op.drop_index(op.f('ix_transactions_external_reference'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('support_tickets')
    op.drop_table('risk_alerts')
    op.drop_table('provider_connections')
    op.drop_table('passport_shares')
    op.drop_table('consents')
    op.drop_table('business_members')
    op.drop_table('savings_goals')
    op.drop_table('financial_passports')
    op.drop_table('businesses')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_refresh_tokens_token_hash'), table_name='admin_refresh_tokens')
    op.drop_table('admin_refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_providers_code'), table_name='providers')
    op.drop_table('providers')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
